AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >-
  Request count scaling stack.

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
    Default: "dev"
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template, provided by the deployment pipeline
    Default: "none"
  VpcStackName:
    Type: String
    Description: >
      The name of the stack that defines the VPC in which resources will be located, provided by the deployment pipeline
  ECSClusterName:
    Type: String
  ECSServiceName:
    Type: String
  ApplicationLoadBalancerName:
    Type: String
  ContainerAutoScalingTarget:
    Type: String

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Mappings:
  EnvConfig:
    dev:
      LambdaLogLevel: DEBUG
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables #pragma: allowlist secret
    build:
      LambdaLogLevel: INFO
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables #pragma: allowlist secret
    staging:
      LambdaLogLevel: INFO
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables #pragma: allowlist secret
    integration:
      LambdaLogLevel: INFO
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables #pragma: allowlist secret
    production:
      LambdaLogLevel: INFO
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables #pragma: allowlist secret

Globals:
  Function:
    AutoPublishAlias: live
    Layers:
      - "arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_323_2_20250822-051314_with_collector_nodejs:1"
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    VpcConfig:
      SubnetIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdC
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
    Timeout: 15
    MemorySize: 128
    Architectures:
      - arm64
    Runtime: nodejs22.x
    CodeUri: ../../
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
        NODE_ENV: "production"
        POWERTOOLS_LOG_LEVEL:
          !FindInMap [EnvConfig, !Ref Environment, LambdaLogLevel]
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        AWS_XRAY_CONTEXT_MISSING: IGNORE_ERROR
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}" #pragma: allowlist secret
          - SecretArn:
              !FindInMap [EnvConfig, !Ref Environment, dynatraceSecretArn]
        DT_CONNECTION_BASE_URL: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}" #pragma: allowlist secret
          - SecretArn:
              !FindInMap [EnvConfig, !Ref Environment, dynatraceSecretArn]
        DT_CLUSTER_ID: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}" #pragma: allowlist secret
          - SecretArn:
              !FindInMap [EnvConfig, !Ref Environment, dynatraceSecretArn]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}" #pragma: allowlist secret
          - SecretArn:
              !FindInMap [EnvConfig, !Ref Environment, dynatraceSecretArn]
        DT_TENANT: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}" #pragma: allowlist secret
          - SecretArn:
              !FindInMap [EnvConfig, !Ref Environment, dynatraceSecretArn]
        DT_LOGGING_NODEJS_FLAGS: Exporter=true,LambdaSensor=false
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: true
        DT_OPEN_TELEMETRY_ALLOW_EXPLICIT_PARENT: true

Resources:
  ALBRequestCountScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ALBRequestCountScaleOutPolicy
      PolicyType: StepScaling
      ResourceId: !Join
        - "/"
        - - "service"
          - !Ref ECSClusterName
          - !Ref ECSServiceName
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 100
            ScalingAdjustment: 1 # Add 1 task if requests are 201–300
          - MetricIntervalLowerBound: 100
            MetricIntervalUpperBound: 300
            ScalingAdjustment: 2 # Add 2 tasks if requests are 301–500
          - MetricIntervalLowerBound: 300
            ScalingAdjustment: 3 # Add 3 tasks if requests > 500

  ALBRequestCountScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ALBRequestCountScaleInPolicy
      PolicyType: StepScaling
      ResourceId: !Join
        - "/"
        - - "service"
          - !Ref ECSClusterName
          - !Ref ECSServiceName
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        StepAdjustments:
          - MetricIntervalUpperBound: -100
            ScalingAdjustment: -2 # Requests < 100
          - MetricIntervalLowerBound: -100
            MetricIntervalUpperBound: 0
            ScalingAdjustment: -1 # Requests between 100–200

  ALBRequestCountScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "ALB-RequestCount-High"
      Metrics:
        - Id: reqCount
          Label: ALB Request Count
          MetricStat:
            Metric:
              Namespace: AWS/ApplicationELB
              MetricName: RequestCount
              Dimensions:
                - Name: LoadBalancer
                  Value: !Ref ApplicationLoadBalancerName
            Period: 60
            Stat: Sum
          ReturnData: false

        - Id: deployFlag
          Label: Deployment In Progress
          MetricStat:
            Metric:
              Namespace: Custom/ECS
              MetricName: DeploymentInProgress
              Dimensions:
                - Name: ClusterName
                  Value: !Ref ECSClusterName
                - Name: ServiceName
                  Value: !Ref ECSServiceName
            Period: 60
            Stat: Minimum
          ReturnData: false

        # Metric 3: Adjusted CPU using metric math
        - Id: adjustedReqCount
          Label: High Request count If Not Deploying
          Expression: IF(deployFlag > 0, 0, reqCount)
          ReturnData: true
      AlarmDescription: "ALB-RequestCount-Above-Threshold"
      DatapointsToAlarm: "1"
      ComparisonOperator: "GreaterThanThreshold"
      EvaluationPeriods: 1
      Threshold: "2000"
      TreatMissingData: "notBreaching"
      ActionsEnabled: true
      AlarmActions:
        - !Ref ALBRequestCountScaleOutPolicy

  ALBRequestCountScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "ALB-RequestCount-Normal"
      MetricName: "RequestCountPerTarget"
      ActionsEnabled: true
      AlarmActions:
        - !Ref ALBRequestCountScaleInPolicy
      AlarmDescription: "ALB-RequestCount-Below-200"
      DatapointsToAlarm: "1"
      Namespace: AWS/ApplicationELB
      ComparisonOperator: "LessThanThreshold"
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ApplicationLoadBalancerName
        - Name: TargetGroup
          Value: !Ref ContainerAutoScalingTarget
      Statistic: Sum
      Period: "60"
      EvaluationPeriods: 1
      Threshold: "1000"
      TreatMissingData: "notBreaching"

  ECSDeploymentInProgressAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "ECS-Deployment-In-Progress"
      Namespace: "Custom/ECS"
      MetricName: DeploymentInProgress
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref ECSServiceName
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmDescription: Alarm is ALARM when ECS is deploying

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ecs-deployment-metric-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref AllowECSAndCloudWatch
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  AllowECSAndCloudWatch:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ecs:DescribeServices
              - cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

  CloudWatchEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: AWS KMS key for encrypting CloudWatch logs
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-CloudWatchEncryptionKey"

  ECSDeploymentMetricLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Creates a deployment metric lambda"
      FunctionName: !Sub ${Environment}-${AWS::StackName}-ecs-status
      Runtime: nodejs22.x
      Handler: ecs-status-handler.handler
      LoggingConfig:
        LogGroup: !Ref ECSDeploymentMetricLambdaLogGroup
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          ECS_CLUSTER: !Ref ECSClusterName
          ECS_SERVICE: !Ref ECSServiceName
          METRIC_NAMESPACE: Custom/ECS
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Format: esm
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambda-handlers/ecs-status-handler.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  ECSDeploymentMetricLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/ECSDeploymentMetricLambda"
      RetentionInDays: 30
      KmsKeyId: !GetAtt CloudWatchEncryptionKey.Arn

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Id: ECSDeploymentMetricTarget
          Arn: !GetAtt ECSDeploymentMetricLambda.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ECSDeploymentMetricLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn

Outputs:
  LambdaFunctionName:
    Value: !Ref ECSDeploymentMetricLambda
