version = 0.1

[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "account-mgmt-frontend"
region = "eu-west-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7d9zueiu0w51"
s3_prefix = "account-management-frontend"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
image_repositories = []
tags = "project=\"account-management-frontend\" stage=\"dev\""
parameter_overrides=[
    "VpcStackName=vpc-enhanced"
]