name: Checkov

on:
  pull_request:
  merge_group:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pragma: allowlist secret
        with:
          persist-credentials: false

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@d9d1e5cdc53e3a91f0c4c58db7bc19ee31cac7e5 # pragma: allowlist secret
        with:
          directory: deploy
          output_format: cli
          output_file_path: console
          # TODO jira ticket OLH-4086: Temporary skip - CKV_AWS_124 requires CloudFormation stacks to send event notifications to an SNS topic.
          # Remove once notification_arns has been added to all affected stacks.
          skip_check: CKV_AWS_124
