name: Checkov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pragma: allowlist secret

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@eec884fd62682f5f2b33e303e160d5e2fe8d89ec # pragma: allowlist secret
        with:
          directory: deploy
          skip_check: CKV_AWS_124 # Ensure that AWS CloudWatch Log Group specifies retention days - not required for this project as log groups are created by AWS CDK and have a default retention of 3 years
          soft_fail: false
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@064a406de026ea27990a5b507b56911401ca2f95 # pragma: allowlist secret
        with:
          sarif_file: results.sarif
