name: "End-to-end tests"

on:
  push:
    branches-ignore:
      - main

jobs:
  end_to_end_tests:
    name: "Run end-to-end tests"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Set up Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: .nvmrc

      - name: Install app dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run app
        run: |
          touch .env
          echo '${{ secrets.ENV_VARIABLES }}' >> .env
          docker compose build && docker compose up &

      - name: Install end-to-end-tests dependencies
        run: cd end-to-end-tests && npm ci

      - name: WORKAROUND (install biome manually) - https://github.com/biomejs/biome/issues/4467
        run: cd end-to-end-tests && npm install --no-save @biomejs/cli-linux-x64

      - name: Run lint
        run: cd end-to-end-tests && npm run lint

      - name: Run end-to-end tests
        run: |
          cd end-to-end-tests

          until curl --output /dev/null --silent --head --fail http://localhost:6001; do
              printf '.'
              sleep 5
          done

          npm run test
        env:
          TEST_ENVIRONMENT: local
          TEST_REPORT_DIR: cucumber-report
