name: Sonarcloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    name: Run Sonar scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d # pin@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    env:
      API_BASE_URL: http://localhost:6000/api
      AM_API_BASE_URL: http://localhost:5000/api
      GOV_ACCOUNTS_PUBLISHING_API_URL: http://localhost:1000/api
      GOV_ACCOUNTS_PUBLISHING_API_TOKEN: token
      AM_YOUR_ACCOUNT_URL: some url
      OIDC_CLIENT_ID: test
      OIDC_CLIENT_SCOPES: openid
      SESSION_SECRET: secret #pragma: allowlist secret
      SESSION_EXPIRY: 3600000
      SESSION_STORE_TABLE_NAME: account-mgmt-frontend-SessionStore
