name: Sonarcloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    name: Run Sonar scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # pin@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm run install-all
      - name: Generate coverage report
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # pin@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    env:
      API_BASE_URL: http://localhost:6000/api
      AM_API_BASE_URL: http://localhost:5000/api
      GOV_ACCOUNTS_PUBLISHING_API_URL: http://localhost:1000/api
      GOV_ACCOUNTS_PUBLISHING_API_TOKEN: token
      AM_YOUR_ACCOUNT_URL: some url
      OIDC_CLIENT_ID: test
      OIDC_CLIENT_SCOPES: openid
      SESSION_SECRET: secret
      SESSION_EXPIRY: 3600000
      SESSION_STORE_TABLE_NAME: account-mgmt-frontend-SessionStore
