---
name: "Build & Scan Docker Image against Dev Env"

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/validate-docker-image-dev.yml"
    branches-ignore:
      - main
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  validate_image:
    name: "Image Checks"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: Set tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Get current date
        id: datetime
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # pin@v1-node16
        with:
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # pin@v1

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@3864d6aed8ff134b2ed894ce00c87695c709c870
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

      - name: Build Docker Image
        id: build-image
        env:
          DEV_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DEV_ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$IMAGE_TAG .
