name: Validate passkeys convenience metadata

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Validate passkeys convenience metadata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm run install-all

      - name: Validate passkeys convenience metadata
        run: |
          npx tsx -e '
            import { getAllPasskeyConvenienceMetadata } from "./src/utils/passkeysConvenienceMetadata/index.ts";

            getAllPasskeyConvenienceMetadata().then((metadata) => {
              console.log("Metadata is valid");
            }).catch((err: unknown) => {
              throw err
            });
          '
